services:
  - type: web
    name: biblioteca-backend-frontend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://postgres:Enrique1234@Jhin@db.mtjrxenjffwjytjfkock.supabase.co:5432/postgres
      - key: DB_HOST
        value: db.mtjrxenjffwjytjfkock.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: Enrique1234@Jhin
      - key: DB_NAME
        value: postgres
      - key: JWT_SECRET
        value: biblioverso-chave-secreta-producao-2024
      - key: CORS_ORIGIN
        value: https://biblioteca-backend-frontend.onrender.com
