services:
  # Backend API
  - type: web
    name: biblio-verso-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        value: db.mtjrxenjffwjytjfkock.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: Enrique1234@Jhin
      - key: DB_NAME
        value: postgres
      - key: JWT_SECRET
        value: biblioverso-chave-secreta-producao-2024
      - key: CORS_ORIGIN
        value: https://biblioteca-backend-frontend.onrender.com
